# config/logging.yaml

version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    level: INFO
    stream: ext://sys.stdout

  file_handler:
    class: logging.handlers.RotatingFileHandler
    formatter: standard
    level: DEBUG
    filename: logs/bot.log
    maxBytes: 10485760  # 10 MB
    backupCount: 5
    encoding: utf8

loggers:
  binance_bot:
    handlers: [console, file_handler]
    level: DEBUG
    propagate: no

root:
  handlers: [console, file_handler]
  level: INFO
